name: CI - Code Quality - Next app

on:
  push:
    paths:
      - 'owl-next-app/**'
      
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'owl-next-app/**'

jobs:
  quality-checks:
    name: Run Linters and Formatters
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: owl-next-app/package-lock.json

      - name: Install dependencies
        working-directory: ./owl-next-app
        run: npm ci

      - name: Run ESLint check
        working-directory: ./owl-next-app
        run: npm run lint

      - name: Run Prettier check
        working-directory: ./owl-next-app
        run: npm run format:check
